In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pl
import pandasql as sq

%matplotlib inline

In [4]:
numeric = pd.read_csv('../datasets/only_numeric.csv')
numeric.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1503424 entries, 0 to 1503423
Data columns (total 4 columns):
Unnamed: 0          1503424 non-null int64
price               1503424 non-null float64
image_top_1         1503424 non-null float64
deal_probability    1503424 non-null float64
dtypes: float64(3), int64(1)
memory usage: 45.9 MB


In [5]:
from sklearn import model_selection
numericY = numeric['deal_probability']
numericX = numeric.drop('deal_probability', axis=1)

X_train, X_test, y_train, y_test = model_selection.train_test_split(numericX, numericY, test_size=0.30)

from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit(X_train, y_train)

y_pred = reg.predict(X_test)

from sklearn import metrics
rmse = metrics.mean_squared_error(y_test, y_pred)
print rmse

0.0783165207207


In [25]:
from sklearn import feature_selection as fs
fs.f_classif(X_train, y_train)

(array([  0.99133899,   2.27467854,  17.91148088]),
 array([ 0.7801275,  0.       ,  0.       ]))

In [28]:
itemseq = pd.read_csv('../datasets/itemseq.csv')
itemseq.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1503424 entries, 0 to 1503423
Data columns (total 5 columns):
Unnamed: 0          1503424 non-null int64
price               1503424 non-null float64
item_seq_number     1503424 non-null int64
image_top_1         1503424 non-null float64
deal_probability    1503424 non-null float64
dtypes: float64(3), int64(2)
memory usage: 57.4 MB


In [29]:
itemseqY = itemseq['deal_probability']
itemseqX = itemseq.drop('deal_probability', axis=1)

X_train, X_test, y_train, y_test = model_selection.train_test_split(itemseqX, itemseqY, test_size=0.30)

from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit(X_train, y_train)

y_pred = reg.predict(X_test)

from sklearn import metrics
rmse = metrics.mean_squared_error(y_test, y_pred)
print rmse

0.065720638094


In [30]:
fs.f_classif(X_train, y_train)

(array([  9.99115396e-01,   6.87602245e-03,   8.46350244e+00,
          1.79094546e+01]),
 array([ 0.53004273,  1.        ,  0.        ,  0.        ]))